### ISSUE TITLE
monitrc leftover and the missing /var/lib/monit

### ISSUE THREAD

**Issue by roozbehf** [pgolm/ansible-playbook-monit#27]
Hi,

First, thanks for the nice ansible role! It was a pleasure using it. 

Running it against my CentOS7 box, I noticed two problems with the configuration:

1. Despite the RedHat variables setting the default config file to be `/etc/monit.conf`, the original `/etc/monitrc` still remains and is loaded when the service starts and the two configurations are merged. In addition to the ambiguity it causes, a dangerous effect is that the default user/pass of `admin:monit` will still be active which is a security issue. 

2. I changed the value of the variable `monitrc_conf` to `/etc/monitrc` to avoid having both files on the system. This revealed another issue: the Ansible configuration file (`templates/monitrc.j2`) sets the id and state of the service to be in the `/var/lib/monit` folder, while this folder does not exist (at least not on my box). This causes the service to complain and fail to start. 

I fixed these issues and a patch of the fix is attached. I can do a pull request if you agree with the changes (commit: https://github.com/roozbehf/ansible-playbook-monit/commit/f1c8f85efa09cb668c48db00a00b5282dd03d991) 

[fix_monitrc_conflict_on_centos7.patch.txt](https://github.com/pgolm/ansible-playbook-monit/files/162083/fix_monitrc_conflict_on_centos7.patch.txt)

**Comment by pgolm** [comment]
Hi,

thanks for your help to improve this playbook. I think that pull requests are a good way to discuss about changes. So feel free to open one the next time.
